[package]
edition = "2024"
name = "wesl-lelwel"
version = "0.1.0"

[dependencies]
codespan-reporting = "0.11"
lexer = { path = "../lexer" }

[build-dependencies]
lelwel = { git = "https://github.com/0x2a-42/lelwel.git" }
